### ISSUE TITLE
Accès + Remarque

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/schema-hautes-remunerations#1]
Salut Mario,
Bravo pour ce schéma.
Peux-tu me passer  en contributeur de celui-ci, j'aimerai ajouter un fichier XLSX valide (car aujourd'hui tu as une erreur dans le build).
De plus, j'ai une remarque sur le champs ```duree_cumulee_mois``` : es-tu sûr que ce soit nécessaire ? Pourrait-on le passer en facultatif ?

**Comment by geoffreyaldebert** [comment]
PR #2 pour le premier point

**Comment by geoffreyaldebert** [comment]
Pour info, le schéma est désormais référencé ici : https://schema.data.gouv.fr/documentation/schemas-investigation-construction comme schéma "en cours d'investigation"

**Comment by ghost** [comment]
Merci pour le fichier XLSX !

Concernant le champs `duree_cumulee_mois`, il n'est pas explicitement prévu par la [loi n° 2019-828 du 6 août 2019](https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000038889209), mais il figure dans [une fiche méthodologique distribuée par la DGCL](http://www.nicecotedazur.org/uploads/media_items/lettre-circulaire-hautes-remunerations.original.pdf).

Je ne sais pas si c'est pertinent, mais la note précise également :

> Les 10 plus hautes rémunérations sur l'année civile sont déterminées à partir des rémunérations brutes non redressées du temps partiel ou de la durée d'emploi de l'agent.
> Par exemple, si un agent entre en fonction en milieu d'année, sa rémunération annuelle considérée ici sera la moitié de celle qu'il aurait perçue s'il avait occupé le poste toute l'année.

**Comment by geoffreyaldebert** [comment]
Ok. Gardons le pour le moment dans ce cas. Je close l'issue.
